### ISSUE TITLE
xrandr: cannot find output "VIRTUAL1"

### ISSUE THREAD

**Issue by hacknlove** [brunodles/linux-second-screen#4]
It does not work, and I cannot find how to fix it

**Comment by FindHao** [comment]
Me too. Under debian 9 with nvidia card.

**Comment by FindHao** [comment]
```shell
./monitor.sh 1200x825 -v v1 -left 
Possible IPs, use 'ifconfig' to check it out, if you want
./monitor.sh:行74: ifconfig: 未找到命令

device  = 1200x825
host    = 1920x1080
scale   = .76
Display = VIRTUAL1
virtual = 1584x1080

xrandr --newmode "1584x1080_20.00"   43.00  1584 1624 1776 1968  1080 1083 1093 1096 -hsync +vsync
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  16 (RRCreateMode)
  Serial number of failed request:  33
  Current serial number in output stream:  33
xrandr --addmode VIRTUAL1 "1584x1080_20.00"
xrandr: cannot find output "VIRTUAL1"
```

**Comment by codebude** [comment]
Seems like a problem with the proprietary Nvidia drivers. Maybe we can write a workaround with disper?
 https://askubuntu.com/questions/27520/xrandr-cant-add-new-mode-with-nvidia-driver

**Comment by brunodles** [comment]
@FindHao it have failed to add the mode `"1584x1080_20.00"` and then it failed to add the following commands.

Can you look if there's another way to create to create a `modeline`?

The idea is to create a virtual display and connect to it using vnc.

**Comment by lauritsriple** [comment]
Same issue. With arch 4.14.13, nvidia 387.34 and Nvidia GTX 970 graphics card. Did you guys get any further with disper? Whenever I try to use it I get segmentation faults.

**Comment by rzfzr** [comment]
Samething with kubunu 18.04/Plasma 5.12.5, no luck.
Tried to use the other listed output from `xrandr`, in my case DP-3, however it gives me `xrandr: Configure crtc 1 failed` when I try `xrandr --output DP-3 --mode 1280x800_60.00 --left-of LVDS-1`
Looking into it

**Comment by asamsulfat** [comment]
I do failed too, 'xrandr: Configure crtc 1 failed".
there is 4 option, DP-1, HDMI-1, HDMI-2 and eDP-1 (currently active)
can't active the other 3 with 'xrandr --output DP-1/other'

but I can trigger HDMI-2 active by plug in HDMI to VGA connector, after HDMI-2 active.
I can pull the HDMI connector from my HDMI port, and HDMI-2 still works.

**Comment by rzfzr** [comment]
I did not find a actual solution, was distro hoping at the time and went from debian to arch based and it simply works out of the box, I had tried different windows managers and they altered nothing so it must be the xorg implementation or something

**Comment by Gia90** [comment]
The solution would be to create the following file:
`sudo vim /usr/share/X11/xorg.conf.d/20-intel.conf`
with the following content:
```
Section "Device"
    Identifier "intelgpu0"
    Driver "intel"
    Option "VirtualHeads" "2"
EndSection
```
and the logout/re-login.

source: https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg

**Comment by brunodles** [comment]
Thanks for all your contribution, I'll add a setup script to create the file as suggested by @Gia90.

**Comment by recolic** [comment]
> The solution would be to create the following file:
> `sudo vim /usr/share/X11/xorg.conf.d/20-intel.conf`
> with the following content:
> 
> ```
> Section "Device"
>     Identifier "intelgpu0"
>     Driver "intel"
>     Option "VirtualHeads" "2"
> EndSection
> ```
> and the logout/re-login.
> 
> source: https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg

After adding this file, it says "No devices detected (EE) no screens found (EE)".

**Comment by sangorys** [comment]
> The solution would be to create the following file:
> `sudo vim /usr/share/X11/xorg.conf.d/20-intel.conf`
> with the following content:
> 
> ```
> Section "Device"
>     Identifier "intelgpu0"
>     Driver "intel"
>     Option "VirtualHeads" "2"
> EndSection
> ```
> 
> and the logout/re-login.
> 
> source: https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg

This solution does not work on my computer with the intel i915 driver.
What works is what is : 

- Install  xserver-xorg-video-dummy
- Update xorg.conf

Details here : https://askubuntu.com/questions/453109/add-fake-display-when-no-monitor-is-plugged-in

**Comment by forliuyifei** [comment]
> The solution would be to create the following file:
> `sudo vim /usr/share/X11/xorg.conf.d/20-intel.conf`
> with the following content:
> 
> ```
> Section "Device"
>     Identifier "intelgpu0"
>     Driver "intel"
>     Option "VirtualHeads" "2"
> EndSection
> ```
> 
> and the logout/re-login.
> 
> source: https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg

You should WARNING that this may cause the computer can't enter the DE, login in with tty and rm it will solve.

**Comment by forliuyifei** [comment]
> > The solution would be to create the following file:
> > `sudo vim /usr/share/X11/xorg.conf.d/20-intel.conf`
> > with the following content:
> > ```
> > Section "Device"
> >     Identifier "intelgpu0"
> >     Driver "intel"
> >     Option "VirtualHeads" "2"
> > EndSection
> > ```
> > 
> > 
> > and the logout/re-login.
> > source: https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg
> 
> This solution does not work on my computer with the intel i915 driver.
> What works in my situation is :
> 
> * Install  xserver-xorg-video-dummy
> * Update xorg.conf
> 
> Details here : https://askubuntu.com/questions/453109/add-fake-display-when-no-monitor-is-plugged-in

Could you tell me how to "Update xorg.conf" ? I have no idea what should I write into it :cry: 
I really need a way to using my Android laptop as the second screen.

**Comment by MostHated** [comment]
> Could you tell me how to "Update xorg.conf" ? I have no idea what should I write into it cry
> I really need a way to using my Android laptop as the second screen.

It's in the link he shared. https://askubuntu.com/a/463000/592487
